---
- name: Ping check to server
  hosts: my_ec2_instance
  tasks:
    - name: Ping server
      ping:
- name: "AWS - Install docker"
  hosts: my_ec2_instance
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python3.9
        - ansible
        - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      remote_user: ec2-user
      get_url: 
        url : https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 'u+x,g+x,o+x'
    - name: Add user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true
      register: add_to_docker_group_result

- name: Install Jenkins and configure Docker permissions
  hosts: my_ec2_instance
  become: true
  tasks:
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true

    - name: Import Jenkins-CI key
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      become: true

    - name: Install Java
      yum:
        name: java-17-amazon-corretto-devel
        state: present
      become: true

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      become: true

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
      become: true
    - name: Add user to docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true
      register: add_to_docker_group_result       
    - name: Allow jenkins to execute docker commands without password
      lineinfile:
        path: /etc/sudoers
        line: "jenkins ALL=(ALL) NOPASSWD: /usr/bin/docker"
        validate: 'visudo -cf %s'
        state: present
      notify: restart jenkins service
    - name: Jenkins init password 
      ansible.builtin.shell:  cat /var/lib/jenkins/secrets/initialAdminPassword
      register: output
    - debug: var=output.stdout_lines
  handlers:
    - name: restart jenkins service
      service:
        name: jenkins
        state: restarted
- name: Install nginx
  hosts: my_ec2_instance
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
      become: true
    - name: remove nginx configure
      file: 
        path: /etc/nginx
        state: absent
    - name: copy nginx files
      ansible.builtin.copy:
        src: /home/ec2-user/jenkins/jenkins-nginx/nginx
        dest: /etc/
        remote_src: yes
    - name: start service nginx
      service:
        name: nginx
        state: restarted